"""config overrides

Revision ID: 5a8ce1fa5469
Revises: 0ff3a2e16d35
Create Date: 2026-08-05 13:30:09.145403
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5a8ce1fa5469'
down_revision: Union[str, None] = '0ff3a2e16d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_overrides',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('secret', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_overrides')
    # ### end Alembic commands ###
